<a href="https://colab.research.google.com/github/Diksha57-git/100-python-projects/blob/main/NumpyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**


### **ARRAY**

In [ ]:
import numpy as np

In [ ]:
# 1. Create a 1D NumPy array containing numbers from 0 to 9.
arr= np.array([0,1,2,3,4,5,6,7,8,9]) # Mistake: Forgot ()
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 2. Create a 3x3 matrix filled entirely with True boolean values.
arr=np.ones((3,3),dtype=bool) #Used np.ones function which created a 3x3 matrics with data type boolean and we can also use np.full((3, 3), True) to explicitly fill the matrix with any value you want.
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# 3. Generate a 1D array of 10 evenly spaced elements between the values of 5 and 50.
arr=np.linspace(5,50,10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [ ]:
# 4. Create a 4x4 identity matrix.
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# 5. Create an array of size 10 filled with zeros, but change the fifth value to 1.
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


####**Slicing and Indexing**

In [ ]:
#  Convert a 1D array of length 12 into a 2D array with 3 rows and 4 columns.
arr=np.arange(12)
a=arr.reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Given a 4x4 matrix, extract the inner 2x2 sub-matrix (excluding the border rows and columns).
matrix = np.array([[ 1,  2,  3,  4],
                   [ 5,  6,  7,  8],
                   [ 9, 10, 11, 12],
                   [13, 14, 15, 16]])
n=matrix[1:3,1:3] # matrix[row_start:row_ends,col_start:col_ends]
print(n)

[[ 6  7]
 [10 11]]


In [ ]:
# Reverse the order of rows in a given 2D NumPy array.
matrix =np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
rev=matrix[::-1]
print(rev)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
# Extract all the odd numbers from a 1D array containing integers from 1 to 20.
arr = np.arange(1, 21)
n=arr[0:21:2]
a=arr[arr % 2 != 0]
print("first method",n)
print("second method",a)

first method [ 1  3  5  7  9 11 13 15 17 19]
second method [ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# Replace all even numbers in an integer array with the value -1 without modifying the original array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a=np.copy(arr)
a[a%2==0]=-1
print(a)

[ 1 -1  3 -1  5 -1  7 -1  9]


####**Array Manipulations & Conditionals**

In [ ]:
# 11. Find the indices of all non-zero elements in the array [1, 0, 2, 0, 3, 0]
arr = np.array([1, 0, 4, 0, 0, 5, 8])
arr= np.where(arr!=0)[0]
print(arr)

[0 2 5 6]


In [ ]:
# 12. Given two 1D arrays, extract all the unique common elements between them.
array1 = np.array([1, 2, 3, 2, 4, 1])
array2 = np.array([2, 3, 5, 6])
np.intersect1d(array1,array2)

array([2, 3])

In [ ]:
# 13. Find the positions where elements of two identical-shaped arrays match exactly.
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 2, 4, 7])
np.where(a==b)

(array([0, 3]),)

In [ ]:
# 14. Stack two 2D arrays both vertically and horizontally.
a = np.zeros((2, 2))
b = np.ones((2, 2))
np.vstack((a,b))
# np.hstack((a,b))

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# 15. Extract all numbers between 5 and 10 (inclusive) from a random float array.
arr = np.array([2, 6, 11, 8, 5, 3, 10, 1])
res=arr[(arr >= 5) & (arr <= 10)]
print(res)

[ 6  8  5 10]


####**Math, Statistics & Linear Algebra**

In [ ]:
# 16. Compute the element-wise absolute differences between two numeric arrays.
a = np.array([10, 20, 30])
b = np.array([12, 15, 33])
np.abs(a-b)

array([2, 5, 3])

In [ ]:
# 17. Find the mean, median, and standard deviation of a 2D matrix along its columns.
matrix = np.array([[1, 4, 7],
                   [3, 6, 9]])
arr=np.mean(matrix,axis=0)
arr2=np.median(matrix,axis=0)
arr3=np.std(matrix,axis=0)
print(arr,arr2,arr3)

[2. 5. 8.] [2. 5. 8.] [1. 1. 1.]


In [ ]:
# 18. Given a 5x5 matrix, subtract the mean of each row from its respective row elements.
matrix = np.array([[10, 20, 30],
                   [70, 80, 90]])
row_mean = matrix -matrix.mean(axis=1,keepdims=True)
print(row_mean)

[[-10.   0.  10.]
 [-10.   0.  10.]]


In [ ]:
# 19. Perform matrix multiplication (dot product) on a 3x2 matrix and a 2x3 matrix.
a = np.array([[1, 2],
              [5, 6],
              [7,8]]) # Shape: (3, 2)

b = np.array([[7, 8, 9],
              [1, 2, 3]])  # Shape: (2, 3)

np.dot(a,b)

array([[ 9, 12, 15],
       [41, 52, 63],
       [57, 72, 87]])

In [ ]:
# 20. Compute the min-max normalization of a 1D array (scale all values between 0 and 1).
arr = np.array([10, 20, 30, 40, 50])
# \(\text{normalized}=\frac{\text{arr}-\text{min}}{\text{max}-\text{min}}\)
a= arr.min()
b=arr.max()
normalized = ((arr-a)/(b-a))
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


####**Advanced Vectorization**

In [ ]:
# 21. Create a 5x5 matrix where the values in each row range strictly from 0 to 4.
arr=np.zeros((5,5))
arr+=np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# 22. Find the most frequent value (mode) in an integer array without using external libraries like SciPy.
arr = np.array([1, 3, 2, 3, 2, 3, 4, 3, 1])
np.bincount(arr).argmax()

np.int64(3)

In [ ]:
# 23. Replace the maximum value in a random 1D vector with 0.
arr = np.array([15, 42, 8, 23, 42, 16])
arr[arr.argmax()]=0
print(arr)

[15  0  8 23 42 16]


In [ ]:
# 24. Given a 1D array, compute a rolling/moving average using a window size of 3.
arr = np.array([10, 20, 30, 40, 50])
np.convolve(arr, np.ones(3)/3, mode='valid')

array([20., 30., 40.])

In [ ]:
# 25 Convert a 10x2 matrix representing Cartesian coordinates (x, y) into Polar coordinates \((r, \theta)\).
import numpy as np

# Your Cartesian coordinate matrix (x, y)
# Row 0: x=3, y=4,  # Row 1: x=5, y=12,   # Row 2: x=1, y=1,   # Row 3: x=0, y=2
    # [-1, -1]  # Row 4: x=-1, y=-1
cartesian = np.array([[3,4],
                     [5,12],
                     [1,1],
                     [0,2],
                     [-1, -1]])

# Get radius (r)
r = np.sqrt(cartesian[:, 0]**2 + cartesian[:, 1]**2)

# Get angle (theta)
theta = np.arctan2(cartesian[:, 1], cartesian[:, 0])

print("r:", r)
print("theta:", theta)


r: [ 5.         13.          1.41421356  2.          1.41421356]
theta: [ 0.92729522  1.17600521  0.78539816  1.57079633 -2.35619449]
